package com.github.xandergos.terraindiffusionmc.pipeline;

// Generated by pack scripts/m1-catalog-filter/generate-bindings.py.
// Exact #3 resource bindings only; no environmental or spatial policy.
final class TerralithCatalogBindings {
    private TerralithCatalogBindings() {}
    static final String[][] RESOURCES = {
        {},
        {"ultira:ocean/terralith_deep_warm_ocean/r001-01", "ultira:ocean/terralith_deep_warm_ocean/r001-02"}, // r001
        {"ultira:ocean/minecraft_ocean/r002-01", "ultira:ocean/minecraft_ocean/r002-02"}, // r002
        {"ultira:beach/terralith_gravel_beach/r003-01", "ultira:beach/terralith_gravel_beach/r003-02", "ultira:beach/terralith_gravel_beach/r003-03"}, // r003
        {"ultira:river/terralith_warm_river/r004-01"}, // r004
        {"ultira:cliff/terralith_glacial_chasm/r005-01", "ultira:cliff/terralith_glacial_chasm/r005-02"}, // r005
        {"ultira:cliff/terralith_frozen_cliffs/r006-01", "ultira:cliff/terralith_frozen_cliffs/r006-02"}, // r006
        {"ultira:cliff/terralith_bryce_canyon/r007-01", "ultira:cliff/terralith_bryce_canyon/r007-02"}, // r007
        {"ultira:cliff/terralith_desert_canyon/r008-01", "ultira:cliff/terralith_desert_canyon/r008-02"}, // r008
        {"ultira:cliff/terralith_amethyst_canyon/r009-01"}, // r009
        {"ultira:cliff/terralith_rocky_jungle/r010-01"}, // r010
        {"ultira:cliff/terralith_basalt_cliffs/r011-01", "ultira:cliff/terralith_basalt_cliffs/r011-02"}, // r011
        {"ultira:cliff/terralith_windswept_spires/r012-01"}, // r012
        {"ultira:cliff/terralith_stony_spires/r013-01", "ultira:cliff/terralith_stony_spires/r013-02"}, // r013
        {"ultira:cliff/terralith_granite_cliffs/r014-01"}, // r014
        {"ultira:cliff/terralith_yosemite_cliffs/r015-01"}, // r015
        {"ultira:cliff/terralith_white_cliffs/r016-01"}, // r016
        {"ultira:plateau/terralith_siberian_grove/r017-01", "ultira:plateau/terralith_siberian_grove/r017-02"}, // r017
        {"ultira:plateau/terralith_snowy_badlands/r018-01", "ultira:plateau/terralith_snowy_badlands/r018-02", "ultira:plateau/terralith_snowy_badlands/r018-03", "ultira:plateau/terralith_snowy_badlands/r018-04"}, // r018
        {"ultira:plateau/terralith_glacial_chasm/r019-01", "ultira:plateau/terralith_glacial_chasm/r019-02", "ultira:plateau/terralith_glacial_chasm/r019-03", "ultira:plateau/terralith_glacial_chasm/r019-04"}, // r019
        {"ultira:plateau/terralith_ice_marsh/r020-01", "ultira:plateau/terralith_ice_marsh/r020-02", "ultira:plateau/terralith_ice_marsh/r020-03", "ultira:plateau/terralith_ice_marsh/r020-04"}, // r020
        {"ultira:plateau/terralith_snowy_shield/r021-01", "ultira:plateau/terralith_snowy_shield/r021-02", "ultira:plateau/terralith_snowy_shield/r021-03", "ultira:plateau/terralith_snowy_shield/r021-04"}, // r021
        {"ultira:plateau/terralith_warped_mesa/r022-01", "ultira:plateau/terralith_warped_mesa/r022-02", "ultira:plateau/terralith_warped_mesa/r022-03", "ultira:plateau/terralith_warped_mesa/r022-04", "ultira:plateau/terralith_warped_mesa/r022-05", "ultira:plateau/terralith_warped_mesa/r022-06", "ultira:plateau/terralith_warped_mesa/r022-07", "ultira:plateau/terralith_warped_mesa/r022-08"}, // r022
        {"ultira:plateau/terralith_white_mesa/r023-01", "ultira:plateau/terralith_white_mesa/r023-02", "ultira:plateau/terralith_white_mesa/r023-03", "ultira:plateau/terralith_white_mesa/r023-04", "ultira:plateau/terralith_white_mesa/r023-05", "ultira:plateau/terralith_white_mesa/r023-06", "ultira:plateau/terralith_white_mesa/r023-07", "ultira:plateau/terralith_white_mesa/r023-08"}, // r023
        {"ultira:plateau/terralith_arid_highlands/r024-01", "ultira:plateau/terralith_arid_highlands/r024-03", "ultira:plateau/terralith_arid_highlands/r024-05", "ultira:plateau/terralith_arid_highlands/r024-07"}, // r024
        {"ultira:plateau/terralith_savanna_badlands/r025-01", "ultira:plateau/terralith_savanna_badlands/r025-02", "ultira:plateau/terralith_savanna_badlands/r025-03", "ultira:plateau/terralith_savanna_badlands/r025-04", "ultira:plateau/terralith_savanna_badlands/r025-05", "ultira:plateau/terralith_savanna_badlands/r025-06", "ultira:plateau/terralith_savanna_badlands/r025-07", "ultira:plateau/terralith_savanna_badlands/r025-08", "ultira:plateau/terralith_savanna_badlands/r025-09", "ultira:plateau/terralith_savanna_badlands/r025-10", "ultira:plateau/terralith_savanna_badlands/r025-11", "ultira:plateau/terralith_savanna_badlands/r025-12", "ultira:plateau/terralith_savanna_badlands/r025-13", "ultira:plateau/terralith_savanna_badlands/r025-14", "ultira:plateau/terralith_savanna_badlands/r025-15", "ultira:plateau/terralith_savanna_badlands/r025-16"}, // r025
        {"ultira:plateau/terralith_gravel_desert/r026-01", "ultira:plateau/terralith_gravel_desert/r026-02", "ultira:plateau/terralith_gravel_desert/r026-05", "ultira:plateau/terralith_gravel_desert/r026-06"}, // r026
        {"ultira:plateau/terralith_siberian_taiga/r027-01", "ultira:plateau/terralith_siberian_taiga/r027-03"}, // r027
        {"ultira:plateau/terralith_highlands/r028-01", "ultira:plateau/terralith_highlands/r028-02", "ultira:plateau/terralith_highlands/r028-03", "ultira:plateau/terralith_highlands/r028-04", "ultira:plateau/terralith_highlands/r028-05", "ultira:plateau/terralith_highlands/r028-06", "ultira:plateau/terralith_highlands/r028-07", "ultira:plateau/terralith_highlands/r028-08", "ultira:plateau/terralith_highlands/r028-09", "ultira:plateau/terralith_highlands/r028-10", "ultira:plateau/terralith_highlands/r028-11", "ultira:plateau/terralith_highlands/r028-12", "ultira:plateau/terralith_highlands/r028-13", "ultira:plateau/terralith_highlands/r028-14", "ultira:plateau/terralith_highlands/r028-15", "ultira:plateau/terralith_highlands/r028-16", "ultira:plateau/terralith_highlands/r028-17", "ultira:plateau/terralith_highlands/r028-18", "ultira:plateau/terralith_highlands/r028-19", "ultira:plateau/terralith_highlands/r028-20", "ultira:plateau/terralith_highlands/r028-21", "ultira:plateau/terralith_highlands/r028-22", "ultira:plateau/terralith_highlands/r028-23", "ultira:plateau/terralith_highlands/r028-24"}, // r028
        {"ultira:plateau/minecraft_meadow/r029-01", "ultira:plateau/minecraft_meadow/r029-02", "ultira:plateau/minecraft_meadow/r029-03", "ultira:plateau/minecraft_meadow/r029-04", "ultira:plateau/minecraft_meadow/r029-05", "ultira:plateau/minecraft_meadow/r029-06", "ultira:plateau/minecraft_meadow/r029-07", "ultira:plateau/minecraft_meadow/r029-08", "ultira:plateau/minecraft_meadow/r029-09", "ultira:plateau/minecraft_meadow/r029-10", "ultira:plateau/minecraft_meadow/r029-11", "ultira:plateau/minecraft_meadow/r029-12", "ultira:plateau/minecraft_meadow/r029-13", "ultira:plateau/minecraft_meadow/r029-14", "ultira:plateau/minecraft_meadow/r029-15", "ultira:plateau/minecraft_meadow/r029-16", "ultira:plateau/minecraft_meadow/r029-17", "ultira:plateau/minecraft_meadow/r029-18", "ultira:plateau/minecraft_meadow/r029-19", "ultira:plateau/minecraft_meadow/r029-20", "ultira:plateau/minecraft_meadow/r029-21", "ultira:plateau/minecraft_meadow/r029-22", "ultira:plateau/minecraft_meadow/r029-23", "ultira:plateau/minecraft_meadow/r029-24"}, // r029
        {"ultira:plateau/terralith_highlands/r030-08", "ultira:plateau/terralith_highlands/r030-16", "ultira:plateau/terralith_highlands/r030-24", "ultira:plateau/terralith_highlands/r030-32", "ultira:plateau/terralith_highlands/r030-40", "ultira:plateau/terralith_highlands/r030-48", "ultira:plateau/terralith_highlands/r030-56", "ultira:plateau/terralith_highlands/r030-64"}, // r030
        {"ultira:plateau/terralith_shield/r031-01", "ultira:plateau/terralith_shield/r031-02", "ultira:plateau/terralith_shield/r031-03", "ultira:plateau/terralith_shield/r031-04", "ultira:plateau/terralith_shield/r031-05", "ultira:plateau/terralith_shield/r031-06", "ultira:plateau/terralith_shield/r031-07", "ultira:plateau/terralith_shield/r031-08"}, // r031
        {"ultira:plateau/terralith_forested_highlands/r032-01", "ultira:plateau/terralith_forested_highlands/r032-02", "ultira:plateau/terralith_forested_highlands/r032-03", "ultira:plateau/terralith_forested_highlands/r032-04"}, // r032
        {"ultira:plateau/terralith_temperate_highlands/r033-04", "ultira:plateau/terralith_temperate_highlands/r033-08", "ultira:plateau/terralith_temperate_highlands/r033-12", "ultira:plateau/terralith_temperate_highlands/r033-16"}, // r033
        {"ultira:alpine/terralith_caldera/r034-01"}, // r034
        {"ultira:alpine/terralith_volcanic_crater/r035-01"}, // r035
        {"ultira:alpine/terralith_volcanic_peaks/r036-01"}, // r036
        {"ultira:alpine/terralith_painted_mountains/r037-01"}, // r037
        {"ultira:alpine/terralith_emerald_peaks/r038-01"}, // r038
        {"ultira:alpine/terralith_scarlet_mountains/r039-01"}, // r039
        {"ultira:alpine/terralith_rocky_mountains/r040-01", "ultira:alpine/terralith_rocky_mountains/r040-02"}, // r040
        {"ultira:alpine/terralith_painted_mountains/r041-01", "ultira:alpine/terralith_painted_mountains/r041-04"}, // r041
        {"ultira:montane/terralith_volcanic_crater/r042-02"}, // r042
        {"ultira:montane/terralith_volcanic_peaks/r043-02"}, // r043
        {"ultira:montane/terralith_yellowstone/r044-01", "ultira:montane/terralith_yellowstone/r044-02"}, // r044
        {"ultira:montane/terralith_jungle_mountains/r045-01", "ultira:montane/terralith_jungle_mountains/r045-02"}, // r045
        {"ultira:montane/terralith_cloud_forest/r046-01", "ultira:montane/terralith_cloud_forest/r046-02"}, // r046
        {"ultira:montane/terralith_alpine_grove/r047-01"}, // r047
        {"ultira:montane/terralith_painted_mountains/r048-01", "ultira:montane/terralith_painted_mountains/r048-02", "ultira:montane/terralith_painted_mountains/r048-03", "ultira:montane/terralith_painted_mountains/r048-04"}, // r048
        {"ultira:montane/terralith_arid_highlands/r049-01", "ultira:montane/terralith_arid_highlands/r049-03"}, // r049
        {"ultira:montane/terralith_rocky_mountains/r050-01", "ultira:montane/terralith_rocky_mountains/r050-02"}, // r050
        {"ultira:montane/terralith_siberian_grove/r051-01"}, // r051
        {"ultira:montane/terralith_haze_mountain/r052-01", "ultira:montane/terralith_haze_mountain/r052-02"}, // r052
        {"ultira:highland/terralith_ashen_savanna/r053-01", "ultira:highland/terralith_ashen_savanna/r053-02"}, // r053
        {"ultira:highland/terralith_snowy_shield/r054-01"}, // r054
        {"ultira:highland/terralith_siberian_grove/r055-01"}, // r055
        {"ultira:highland/terralith_gravel_desert/r056-01"}, // r056
        {"ultira:highland/terralith_warped_mesa/r057-01", "ultira:highland/terralith_warped_mesa/r057-02", "ultira:highland/terralith_warped_mesa/r057-03", "ultira:highland/terralith_warped_mesa/r057-04"}, // r057
        {"ultira:highland/terralith_white_mesa/r058-01", "ultira:highland/terralith_white_mesa/r058-02", "ultira:highland/terralith_white_mesa/r058-03", "ultira:highland/terralith_white_mesa/r058-04"}, // r058
        {"ultira:highland/terralith_arid_highlands/r059-01", "ultira:highland/terralith_arid_highlands/r059-02"}, // r059
        {"ultira:highland/terralith_savanna_slopes/r060-01", "ultira:highland/terralith_savanna_slopes/r060-02", "ultira:highland/terralith_savanna_slopes/r060-03", "ultira:highland/terralith_savanna_slopes/r060-04", "ultira:highland/terralith_savanna_slopes/r060-05", "ultira:highland/terralith_savanna_slopes/r060-06", "ultira:highland/terralith_savanna_slopes/r060-07", "ultira:highland/terralith_savanna_slopes/r060-08"}, // r060
        {"ultira:highland/terralith_savanna_badlands/r061-01", "ultira:highland/terralith_savanna_badlands/r061-02", "ultira:highland/terralith_savanna_badlands/r061-03", "ultira:highland/terralith_savanna_badlands/r061-04", "ultira:highland/terralith_savanna_badlands/r061-05", "ultira:highland/terralith_savanna_badlands/r061-06", "ultira:highland/terralith_savanna_badlands/r061-07", "ultira:highland/terralith_savanna_badlands/r061-08"}, // r061
        {"ultira:highland/terralith_fractured_savanna/r062-01", "ultira:highland/terralith_fractured_savanna/r062-02", "ultira:highland/terralith_fractured_savanna/r062-03", "ultira:highland/terralith_fractured_savanna/r062-04", "ultira:highland/terralith_fractured_savanna/r062-05", "ultira:highland/terralith_fractured_savanna/r062-06", "ultira:highland/terralith_fractured_savanna/r062-07", "ultira:highland/terralith_fractured_savanna/r062-08"}, // r062
        {"ultira:highland/terralith_amethyst_rainforest/r063-01", "ultira:highland/terralith_amethyst_rainforest/r063-02", "ultira:highland/terralith_amethyst_rainforest/r063-03", "ultira:highland/terralith_amethyst_rainforest/r063-04", "ultira:highland/terralith_amethyst_rainforest/r063-05", "ultira:highland/terralith_amethyst_rainforest/r063-06", "ultira:highland/terralith_amethyst_rainforest/r063-07", "ultira:highland/terralith_amethyst_rainforest/r063-08"}, // r063
        {"ultira:highland/terralith_rocky_jungle/r064-01", "ultira:highland/terralith_rocky_jungle/r064-02", "ultira:highland/terralith_rocky_jungle/r064-03", "ultira:highland/terralith_rocky_jungle/r064-04", "ultira:highland/terralith_rocky_jungle/r064-05", "ultira:highland/terralith_rocky_jungle/r064-06", "ultira:highland/terralith_rocky_jungle/r064-07", "ultira:highland/terralith_rocky_jungle/r064-08"}, // r064
        {"ultira:highland/terralith_snowy_shield/r065-01"}, // r065
        {"ultira:highland/terralith_siberian_taiga/r066-01"}, // r066
        {"ultira:highland/terralith_alpine_highlands/r067-01", "ultira:highland/terralith_alpine_highlands/r067-02"}, // r067
        {"ultira:highland/terralith_shield/r068-01", "ultira:highland/terralith_shield/r068-02", "ultira:highland/terralith_shield/r068-03", "ultira:highland/terralith_shield/r068-04"}, // r068
        {"ultira:highland/terralith_forested_highlands/r069-01", "ultira:highland/terralith_forested_highlands/r069-02"}, // r069
        {"ultira:highland/terralith_highlands/r070-04", "ultira:highland/terralith_highlands/r070-08"}, // r070
        {"ultira:highland/terralith_temperate_highlands/r071-04", "ultira:highland/terralith_temperate_highlands/r071-08"}, // r071
        {"ultira:upland/terralith_snowy_badlands/r072-01"}, // r072
        {"ultira:upland/terralith_snowy_shield/r073-01"}, // r073
        {"ultira:upland/terralith_snowy_maple_forest/r074-01"}, // r074
        {"ultira:upland/terralith_wintry_forest/r075-01"}, // r075
        {"ultira:upland/terralith_gravel_desert/r076-01"}, // r076
        {"ultira:upland/terralith_warped_mesa/r077-01", "ultira:upland/terralith_warped_mesa/r077-02", "ultira:upland/terralith_warped_mesa/r077-03", "ultira:upland/terralith_warped_mesa/r077-04"}, // r077
        {"ultira:upland/terralith_white_mesa/r078-01", "ultira:upland/terralith_white_mesa/r078-02", "ultira:upland/terralith_white_mesa/r078-03", "ultira:upland/terralith_white_mesa/r078-04"}, // r078
        {"ultira:upland/terralith_desert_spires/r079-01", "ultira:upland/terralith_desert_spires/r079-02"}, // r079
        {"ultira:upland/terralith_lush_desert/r080-01", "ultira:upland/terralith_lush_desert/r080-02"}, // r080
        {"ultira:upland/terralith_sandstone_valley/r081-01", "ultira:upland/terralith_sandstone_valley/r081-02"}, // r081
        {"ultira:upland/terralith_arid_highlands/r082-01", "ultira:upland/terralith_arid_highlands/r082-02"}, // r082
        {"ultira:upland/terralith_cold_shrubland/r083-01", "ultira:upland/terralith_cold_shrubland/r083-02"}, // r083
        {"ultira:upland/terralith_rocky_shrubland/r084-01", "ultira:upland/terralith_rocky_shrubland/r084-02"}, // r084
        {"ultira:upland/terralith_savanna_slopes/r085-01", "ultira:upland/terralith_savanna_slopes/r085-02", "ultira:upland/terralith_savanna_slopes/r085-03", "ultira:upland/terralith_savanna_slopes/r085-04"}, // r085
        {"ultira:upland/terralith_brushland/r086-01", "ultira:upland/terralith_brushland/r086-02", "ultira:upland/terralith_brushland/r086-03", "ultira:upland/terralith_brushland/r086-04"}, // r086
        {"ultira:upland/terralith_hot_shrubland/r087-01", "ultira:upland/terralith_hot_shrubland/r087-02", "ultira:upland/terralith_hot_shrubland/r087-03", "ultira:upland/terralith_hot_shrubland/r087-04"}, // r087
        {"ultira:upland/terralith_shrubland/r088-01", "ultira:upland/terralith_shrubland/r088-02", "ultira:upland/terralith_shrubland/r088-03", "ultira:upland/terralith_shrubland/r088-04"}, // r088
        {"ultira:upland/terralith_steppe/r089-01", "ultira:upland/terralith_steppe/r089-02", "ultira:upland/terralith_steppe/r089-03", "ultira:upland/terralith_steppe/r089-04"}, // r089
        {"ultira:upland/terralith_rocky_jungle/r090-01", "ultira:upland/terralith_rocky_jungle/r090-02", "ultira:upland/terralith_rocky_jungle/r090-03", "ultira:upland/terralith_rocky_jungle/r090-04"}, // r090
        {"ultira:upland/terralith_tropical_jungle/r091-01", "ultira:upland/terralith_tropical_jungle/r091-02", "ultira:upland/terralith_tropical_jungle/r091-03", "ultira:upland/terralith_tropical_jungle/r091-04"}, // r091
        {"ultira:upland/terralith_siberian_taiga/r092-01"}, // r092
        {"ultira:upland/terralith_wintry_forest/r093-01"}, // r093
        {"ultira:upland/terralith_birch_taiga/r094-01", "ultira:upland/terralith_birch_taiga/r094-02", "ultira:upland/terralith_birch_taiga/r094-03", "ultira:upland/terralith_birch_taiga/r094-04"}, // r094
        {"ultira:upland/terralith_shield/r095-01", "ultira:upland/terralith_shield/r095-02", "ultira:upland/terralith_shield/r095-03", "ultira:upland/terralith_shield/r095-04"}, // r095
        {"ultira:upland/terralith_shield_clearing/r096-01", "ultira:upland/terralith_shield_clearing/r096-02"}, // r096
        {"ultira:upland/terralith_yosemite_lowlands/r097-01", "ultira:upland/terralith_yosemite_lowlands/r097-02"}, // r097
        {"ultira:lowland/terralith_ice_marsh/r098-01"}, // r098
        {"ultira:lowland/terralith_orchid_swamp/r099-01", "ultira:lowland/terralith_orchid_swamp/r099-02"}, // r099
        {"ultira:lowland/terralith_snowy_badlands/r100-01"}, // r100
        {"ultira:lowland/terralith_wintry_lowlands/r101-01"}, // r101
        {"ultira:lowland/terralith_snowy_cherry_grove/r102-01"}, // r102
        {"ultira:lowland/terralith_snowy_maple_forest/r103-01"}, // r103
        {"ultira:lowland/terralith_wintry_forest/r104-01"}, // r104
        {"ultira:lowland/terralith_red_oasis/r105-01", "ultira:lowland/terralith_red_oasis/r105-02"}, // r105
        {"ultira:lowland/terralith_desert_oasis/r106-01", "ultira:lowland/terralith_desert_oasis/r106-02"}, // r106
        {"ultira:lowland/terralith_sandstone_valley/r107-01", "ultira:lowland/terralith_sandstone_valley/r107-02"}, // r107
        {"ultira:lowland/terralith_ancient_sands/r108-01", "ultira:lowland/terralith_ancient_sands/r108-02"}, // r108
        {"ultira:lowland/terralith_gravel_desert/r109-01"}, // r109
        {"ultira:lowland/terralith_tropical_jungle/r110-01", "ultira:lowland/terralith_tropical_jungle/r110-02", "ultira:lowland/terralith_tropical_jungle/r110-03", "ultira:lowland/terralith_tropical_jungle/r110-04"}, // r110
        {"ultira:lowland/terralith_cold_shrubland/r111-01", "ultira:lowland/terralith_cold_shrubland/r111-02"}, // r111
        {"ultira:lowland/terralith_hot_shrubland/r112-01", "ultira:lowland/terralith_hot_shrubland/r112-02", "ultira:lowland/terralith_hot_shrubland/r112-03", "ultira:lowland/terralith_hot_shrubland/r112-04"}, // r112
        {"ultira:lowland/terralith_shrubland/r113-01", "ultira:lowland/terralith_shrubland/r113-02", "ultira:lowland/terralith_shrubland/r113-03", "ultira:lowland/terralith_shrubland/r113-04"}, // r113
        {"ultira:lowland/terralith_steppe/r114-01", "ultira:lowland/terralith_steppe/r114-02", "ultira:lowland/terralith_steppe/r114-03", "ultira:lowland/terralith_steppe/r114-04"}, // r114
        {"ultira:lowland/terralith_wintry_lowlands/r115-01"}, // r115
        {"ultira:lowland/terralith_siberian_taiga/r116-01"}, // r116
        {"ultira:lowland/terralith_birch_taiga/r117-01", "ultira:lowland/terralith_birch_taiga/r117-02", "ultira:lowland/terralith_birch_taiga/r117-03", "ultira:lowland/terralith_birch_taiga/r117-04"}, // r117
        {"ultira:lowland/terralith_valley_clearing/r118-01", "ultira:lowland/terralith_valley_clearing/r118-02", "ultira:lowland/terralith_valley_clearing/r118-03", "ultira:lowland/terralith_valley_clearing/r118-04"}, // r118
        {"ultira:lowland/terralith_lush_valley/r119-01", "ultira:lowland/terralith_lush_valley/r119-02"}, // r119
        {"ultira:lowland/terralith_yosemite_lowlands/r120-01", "ultira:lowland/terralith_yosemite_lowlands/r120-02"}, // r120
        {"ultira:plateau/terralith_lavender_forest/r121-01", "ultira:plateau/terralith_lavender_forest/r121-02", "ultira:plateau/terralith_lavender_forest/r121-03", "ultira:plateau/terralith_lavender_forest/r121-04", "ultira:plateau/terralith_lavender_forest/r121-05", "ultira:plateau/terralith_lavender_forest/r121-06", "ultira:plateau/terralith_lavender_forest/r121-07", "ultira:plateau/terralith_lavender_forest/r121-08"}, // r121
        {"ultira:plateau/terralith_sakura_grove/r122-01", "ultira:plateau/terralith_sakura_grove/r122-02", "ultira:plateau/terralith_sakura_grove/r122-03", "ultira:plateau/terralith_sakura_grove/r122-04", "ultira:plateau/terralith_sakura_grove/r122-05", "ultira:plateau/terralith_sakura_grove/r122-06", "ultira:plateau/terralith_sakura_grove/r122-07", "ultira:plateau/terralith_sakura_grove/r122-08"}, // r122
        {"ultira:plateau/terralith_moonlight_grove/r123-01", "ultira:plateau/terralith_moonlight_grove/r123-02", "ultira:plateau/terralith_moonlight_grove/r123-03", "ultira:plateau/terralith_moonlight_grove/r123-04", "ultira:plateau/terralith_moonlight_grove/r123-05", "ultira:plateau/terralith_moonlight_grove/r123-06", "ultira:plateau/terralith_moonlight_grove/r123-07", "ultira:plateau/terralith_moonlight_grove/r123-08"}, // r123
        {"ultira:plateau/terralith_blooming_plateau/r124-01", "ultira:plateau/terralith_blooming_plateau/r124-02", "ultira:plateau/terralith_blooming_plateau/r124-03", "ultira:plateau/terralith_blooming_plateau/r124-04", "ultira:plateau/terralith_blooming_plateau/r124-05", "ultira:plateau/terralith_blooming_plateau/r124-06", "ultira:plateau/terralith_blooming_plateau/r124-07", "ultira:plateau/terralith_blooming_plateau/r124-08"}, // r124
        {"ultira:highland/terralith_lavender_forest/r125-01", "ultira:highland/terralith_lavender_forest/r125-02"}, // r125
        {"ultira:highland/terralith_sakura_grove/r126-01", "ultira:highland/terralith_sakura_grove/r126-02"}, // r126
        {"ultira:highland/terralith_moonlight_grove/r127-01", "ultira:highland/terralith_moonlight_grove/r127-02"}, // r127
        {"ultira:highland/terralith_blooming_plateau/r128-01", "ultira:highland/terralith_blooming_plateau/r128-02"}, // r128
        {"ultira:upland/terralith_lavender_forest/r129-01", "ultira:upland/terralith_lavender_forest/r129-02"}, // r129
        {"ultira:upland/terralith_sakura_grove/r130-01", "ultira:upland/terralith_sakura_grove/r130-02"}, // r130
        {"ultira:upland/terralith_moonlight_grove/r131-01", "ultira:upland/terralith_moonlight_grove/r131-02"}, // r131
        {"ultira:upland/terralith_blooming_plateau/r132-01", "ultira:upland/terralith_blooming_plateau/r132-02"}, // r132
        {"ultira:lowland/terralith_lavender_valley/r133-01", "ultira:lowland/terralith_lavender_valley/r133-02"}, // r133
        {"ultira:lowland/terralith_sakura_valley/r134-01", "ultira:lowland/terralith_sakura_valley/r134-02"}, // r134
        {"ultira:lowland/terralith_moonlight_valley/r135-01", "ultira:lowland/terralith_moonlight_valley/r135-02"}, // r135
        {"ultira:lowland/terralith_blooming_valley/r136-01", "ultira:lowland/terralith_blooming_valley/r136-02"}, // r136
    };
    static final String[] BIOMES = {
        "",
        "terralith:deep_warm_ocean",
        "minecraft:ocean",
        "terralith:gravel_beach",
        "terralith:warm_river",
        "terralith:glacial_chasm",
        "terralith:frozen_cliffs",
        "terralith:bryce_canyon",
        "terralith:desert_canyon",
        "terralith:amethyst_canyon",
        "terralith:rocky_jungle",
        "terralith:basalt_cliffs",
        "terralith:windswept_spires",
        "terralith:stony_spires",
        "terralith:granite_cliffs",
        "terralith:yosemite_cliffs",
        "terralith:white_cliffs",
        "terralith:siberian_grove",
        "terralith:snowy_badlands",
        "terralith:glacial_chasm",
        "terralith:ice_marsh",
        "terralith:snowy_shield",
        "terralith:warped_mesa",
        "terralith:white_mesa",
        "terralith:arid_highlands",
        "terralith:savanna_badlands",
        "terralith:gravel_desert",
        "terralith:siberian_taiga",
        "terralith:highlands",
        "minecraft:meadow",
        "terralith:highlands",
        "terralith:shield",
        "terralith:forested_highlands",
        "terralith:temperate_highlands",
        "terralith:caldera",
        "terralith:volcanic_crater",
        "terralith:volcanic_peaks",
        "terralith:painted_mountains",
        "terralith:emerald_peaks",
        "terralith:scarlet_mountains",
        "terralith:rocky_mountains",
        "terralith:painted_mountains",
        "terralith:volcanic_crater",
        "terralith:volcanic_peaks",
        "terralith:yellowstone",
        "terralith:jungle_mountains",
        "terralith:cloud_forest",
        "terralith:alpine_grove",
        "terralith:painted_mountains",
        "terralith:arid_highlands",
        "terralith:rocky_mountains",
        "terralith:siberian_grove",
        "terralith:haze_mountain",
        "terralith:ashen_savanna",
        "terralith:snowy_shield",
        "terralith:siberian_grove",
        "terralith:gravel_desert",
        "terralith:warped_mesa",
        "terralith:white_mesa",
        "terralith:arid_highlands",
        "terralith:savanna_slopes",
        "terralith:savanna_badlands",
        "terralith:fractured_savanna",
        "terralith:amethyst_rainforest",
        "terralith:rocky_jungle",
        "terralith:snowy_shield",
        "terralith:siberian_taiga",
        "terralith:alpine_highlands",
        "terralith:shield",
        "terralith:forested_highlands",
        "terralith:highlands",
        "terralith:temperate_highlands",
        "terralith:snowy_badlands",
        "terralith:snowy_shield",
        "terralith:snowy_maple_forest",
        "terralith:wintry_forest",
        "terralith:gravel_desert",
        "terralith:warped_mesa",
        "terralith:white_mesa",
        "terralith:desert_spires",
        "terralith:lush_desert",
        "terralith:sandstone_valley",
        "terralith:arid_highlands",
        "terralith:cold_shrubland",
        "terralith:rocky_shrubland",
        "terralith:savanna_slopes",
        "terralith:brushland",
        "terralith:hot_shrubland",
        "terralith:shrubland",
        "terralith:steppe",
        "terralith:rocky_jungle",
        "terralith:tropical_jungle",
        "terralith:siberian_taiga",
        "terralith:wintry_forest",
        "terralith:birch_taiga",
        "terralith:shield",
        "terralith:shield_clearing",
        "terralith:yosemite_lowlands",
        "terralith:ice_marsh",
        "terralith:orchid_swamp",
        "terralith:snowy_badlands",
        "terralith:wintry_lowlands",
        "terralith:snowy_cherry_grove",
        "terralith:snowy_maple_forest",
        "terralith:wintry_forest",
        "terralith:red_oasis",
        "terralith:desert_oasis",
        "terralith:sandstone_valley",
        "terralith:ancient_sands",
        "terralith:gravel_desert",
        "terralith:tropical_jungle",
        "terralith:cold_shrubland",
        "terralith:hot_shrubland",
        "terralith:shrubland",
        "terralith:steppe",
        "terralith:wintry_lowlands",
        "terralith:siberian_taiga",
        "terralith:birch_taiga",
        "terralith:valley_clearing",
        "terralith:lush_valley",
        "terralith:yosemite_lowlands",
        "terralith:lavender_forest",
        "terralith:sakura_grove",
        "terralith:moonlight_grove",
        "terralith:blooming_plateau",
        "terralith:lavender_forest",
        "terralith:sakura_grove",
        "terralith:moonlight_grove",
        "terralith:blooming_plateau",
        "terralith:lavender_forest",
        "terralith:sakura_grove",
        "terralith:moonlight_grove",
        "terralith:blooming_plateau",
        "terralith:lavender_valley",
        "terralith:sakura_valley",
        "terralith:moonlight_valley",
        "terralith:blooming_valley",
    };
    static final short[] TARGETS = {
        0,
        200,
        44,
        201,
        202,
        221,
        210,
        219,
        218,
        220,
        311,
        214,
        216,
        215,
        211,
        213,
        212,
        259,
        298,
        221,
        345,
        258,
        296,
        295,
        253,
        271,
        297,
        340,
        254,
        29,
        254,
        256,
        252,
        251,
        232,
        231,
        230,
        236,
        233,
        234,
        235,
        236,
        231,
        230,
        241,
        238,
        240,
        239,
        236,
        253,
        235,
        259,
        237,
        272,
        258,
        259,
        297,
        296,
        295,
        253,
        270,
        271,
        273,
        312,
        311,
        258,
        340,
        250,
        256,
        252,
        254,
        251,
        298,
        258,
        343,
        341,
        297,
        296,
        295,
        217,
        291,
        294,
        253,
        277,
        260,
        270,
        274,
        276,
        275,
        278,
        311,
        310,
        340,
        341,
        323,
        256,
        257,
        320,
        345,
        331,
        298,
        342,
        344,
        343,
        341,
        293,
        292,
        294,
        290,
        297,
        310,
        277,
        276,
        275,
        278,
        342,
        340,
        323,
        322,
        321,
        320,
        324,
        326,
        328,
        255,
        324,
        326,
        328,
        255,
        324,
        326,
        328,
        255,
        325,
        327,
        329,
        330,
    };
}
